[project]
name = "gamail-access"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "google-auth>=2.38.0",
    "google-auth-oauthlib>=1.2.1",
]
